### ISSUE TITLE
Reload time is unbearable

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-preview#87]
When updating a story while using the build plugin in serve mode, it rebuilds the whole preview. This just take much too long.

**Comment by no-creative-name** [comment]
I'm currently investigating in why Storybook's hot reload functionality does not work in the preview.

**Comment by no-creative-name** [comment]
biotope-preview will is not planned to be used for development but for showcase purposes, thus the serve functionality will stay implemented, but not be improved as of now.
